'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import AppWalletProvider from './components/AppWalletProvider';
import { Footer } from './components/Footer';
import { Suspense } from 'react';
import LoadingPage from './components/LoadingPage';
import { CSPostHogProvider } from './components/AnalyticsProvider';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CSPostHogProvider>
          <SessionProvider>
            <AppWalletProvider>
              <div className="flex flex-col min-h-screen">
                <Suspense fallback={<LoadingPage />}>{children}</Suspense>
                <Footer />
              </div>
            </AppWalletProvider>
          </SessionProvider>
        </CSPostHogProvider>
      </body>
    </html>
  );
}
